# Generated by Django 5.1.15 on 2026-03-23 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('contact', 'Обычная форма'), ('product', 'Заявка с товара'), ('cart', 'Заявка из корзины')], db_index=True, default='contact', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('source_path', models.CharField(blank=True, max_length=500, verbose_name='Страница отправки')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leads', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('category_name', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('product_slug', models.CharField(blank=True, max_length=255, verbose_name='Slug товара')),
                ('product_url', models.CharField(blank=True, max_length=500, verbose_name='URL товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на момент заявки')),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма позиции')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leads.lead', verbose_name='Заявка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_items', to='catalog.product', verbose_name='Текущий товар')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
                'ordering': ('id',),
            },
        ),
    ]
