# Generated by Django 5.1.15 on 2026-03-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referer',
            field=models.TextField(blank=True, verbose_name='Referer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM content'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM medium'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UTM source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM term'),
        ),
        migrations.AddField(
            model_name='lead',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tracking.visitor', verbose_name='Посетитель'),
        ),
    ]
