# Generated by Django 6.0.7 on 2026-09-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_referer_lead_utm_campaign_lead_utm_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('assigned', 'Назначена'), ('in_progress', 'В работе'), ('contacted', 'Контакт установлен'), ('qualified', 'Квалифицирована'), ('completed', 'Успешно закрыта'), ('canceled', 'Закрыта без успеха')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='LeadHandlingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('response_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20)),
                ('result_description', models.TextField(blank=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='leads.lead')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='leads.lead')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='leads.leadhandlingcycle')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.lead')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='leads.leadhandlingcycle')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('messenger', 'Мессенджер'), ('meeting', 'Встреча'), ('other', 'Другое')], max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Контакт состоялся'), ('no_answer', 'Нет ответа'), ('failed', 'Неудача')], max_length=20)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='leads.leadhandlingcycle')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leads.leadevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('response_minutes', models.PositiveIntegerField(default=240)),
                ('resolution_minutes', models.PositiveIntegerField(default=1440)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.slapolicy'),
        ),
        migrations.AddConstraint(
            model_name='leadevent',
            constraint=models.UniqueConstraint(fields=('lead', 'actor', 'idempotency_key'), name='unique_lead_action_key'),
        ),
        migrations.AddConstraint(
            model_name='leadevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['sla_response_overdue', 'sla_resolution_overdue'])), fields=('cycle', 'kind'), name='unique_cycle_sla_alert'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event'), name='unique_event_recipient'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('response_minutes__gt', 0)), name='sla_response_positive'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_minutes__gte', models.F('response_minutes'))), name='sla_resolution_after_response'),
        ),
        migrations.AddConstraint(
            model_name='leadhandlingcycle',
            constraint=models.UniqueConstraint(fields=('lead', 'number'), name='unique_lead_cycle_number'),
        ),
        migrations.AddConstraint(
            model_name='leadhandlingcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('lead',), name='one_open_lead_cycle'),
        ),
        migrations.AddConstraint(
            model_name='leadhandlingcycle',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='cycle_end_after_start'),
        ),
    ]
