# Generated by Django 6.0.7 on 2026-09-21 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_import_existing_leads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadevent',
            name='unique_cycle_sla_alert',
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_remind_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadevent',
            name='reminder_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='priority_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='resolution_warning_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadhandlingcycle',
            name='response_warning_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='priority_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='warning_percent',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddConstraint(
            model_name='leadevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['sla_response_warning', 'sla_response_overdue', 'sla_resolution_warning', 'sla_resolution_overdue'])), fields=('cycle', 'kind'), name='unique_cycle_sla_alert'),
        ),
        migrations.AddConstraint(
            model_name='leadevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['next_action_warning', 'next_action_overdue'])), fields=('lead', 'kind', 'reminder_revision'), name='unique_next_action_alert'),
        ),
        migrations.AddConstraint(
            model_name='leadevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['next_action_warning', 'next_action_overdue']), _negated=True), ('reminder_revision__isnull', False), _connector='OR'), name='next_action_alert_has_revision'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('warning_percent__gte', 1), ('warning_percent__lte', 99)), name='sla_warning_percent_range'),
        ),
    ]
