# Generated by Django 5.1.15 on 2026-03-23 22:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ключ сессии')),
                ('first_ip_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Первый IP hash')),
                ('last_ip_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Последний IP hash')),
                ('first_user_agent', models.TextField(blank=True, verbose_name='Первый User-Agent')),
                ('last_user_agent', models.TextField(blank=True, verbose_name='Последний User-Agent')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Первый визит')),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Просмотр товара'), ('cart_add', 'Добавление в корзину'), ('cart_update', 'Изменение корзины'), ('cart_remove', 'Удаление из корзины'), ('cart_clear', 'Очистка корзины'), ('favorite_add', 'Добавление в избранное'), ('favorite_remove', 'Удаление из избранного'), ('lead_contact_created', 'Создание обычной заявки'), ('lead_product_created', 'Создание заявки с товара'), ('lead_cart_created', 'Создание заявки из корзины'), ('login', 'Вход'), ('signup', 'Регистрация')], db_index=True, max_length=50, verbose_name='Тип события')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Путь')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='leads.lead', verbose_name='Заявка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.product', verbose_name='Товар')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.profile', verbose_name='Профиль')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracking.visitor', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Событие пользователя',
                'verbose_name_plural': 'События пользователей',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at', 'event_type'], name='tracking_us_created_b7eeeb_idx'), models.Index(fields=['product', 'created_at'], name='tracking_us_product_12b5c4_idx'), models.Index(fields=['profile', 'created_at'], name='tracking_us_profile_7e9114_idx'), models.Index(fields=['visitor', 'created_at'], name='tracking_us_visitor_5fa462_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый просмотр')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Последний просмотр')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='Количество просмотров')),
                ('last_path', models.CharField(blank=True, max_length=500, verbose_name='Последний путь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='catalog.product', verbose_name='Товар')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to='accounts.profile', verbose_name='Профиль')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to='tracking.visitor', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'История просмотра товара',
                'verbose_name_plural': 'История просмотров товаров',
                'ordering': ('-last_viewed_at',),
                'indexes': [models.Index(fields=['profile', 'last_viewed_at'], name='tracking_pr_profile_963ffa_idx'), models.Index(fields=['visitor', 'last_viewed_at'], name='tracking_pr_visitor_c0cedb_idx'), models.Index(fields=['product', 'last_viewed_at'], name='tracking_pr_product_30b66a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('profile__isnull', False)), fields=('profile', 'product'), name='unique_product_view_per_profile'), models.UniqueConstraint(condition=models.Q(('profile__isnull', True), ('visitor__isnull', False)), fields=('visitor', 'product'), name='unique_guest_product_view_per_visitor')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='Метод')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Путь')),
                ('full_path', models.CharField(blank=True, max_length=1000, verbose_name='Полный путь')),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Имя маршрута')),
                ('query_string', models.TextField(blank=True, verbose_name='Query string')),
                ('referer', models.TextField(blank=True, verbose_name='Referer')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='IP hash')),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=200, verbose_name='HTTP статус')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мс')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=255, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=255, verbose_name='UTM campaign')),
                ('utm_term', models.CharField(blank=True, max_length=255, verbose_name='UTM term')),
                ('utm_content', models.CharField(blank=True, max_length=255, verbose_name='UTM content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to='accounts.profile', verbose_name='Профиль')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to='tracking.visitor', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Посещение страницы',
                'verbose_name_plural': 'Посещения страниц',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at', 'path'], name='tracking_pa_created_09fa2f_idx'), models.Index(fields=['created_at', 'route_name'], name='tracking_pa_created_93c7a2_idx'), models.Index(fields=['visitor', 'created_at'], name='tracking_pa_visitor_b21f4a_idx'), models.Index(fields=['profile', 'created_at'], name='tracking_pa_profile_da1078_idx')],
            },
        ),
    ]
