# Generated by Django 5.1.15 on 2026-03-23 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Скор')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=20, verbose_name='Приоритет')),
                ('model_name', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='Версия модели')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Признаки')),
                ('explanation', models.JSONField(blank=True, default=dict, verbose_name='Объяснение')),
                ('predicted_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='leads.lead', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Скоринг заявки',
                'verbose_name_plural': 'Скоринги заявок',
                'ordering': ('-predicted_at',),
            },
        ),
        migrations.CreateModel(
            name='PageDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('path', models.CharField(max_length=500, verbose_name='Путь')),
                ('route_name', models.CharField(blank=True, max_length=255, verbose_name='Имя маршрута')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Хиты')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальные посетители')),
                ('unique_users', models.PositiveIntegerField(default=0, verbose_name='Уникальные пользователи')),
                ('unique_profiles', models.PositiveIntegerField(default=0, verbose_name='Уникальные профили')),
                ('avg_duration_ms', models.PositiveIntegerField(default=0, verbose_name='Средняя длительность, мс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дневная метрика страницы',
                'verbose_name_plural': 'Дневные метрики страниц',
                'ordering': ('-date', '-hits'),
                'constraints': [models.UniqueConstraint(fields=('date', 'path', 'route_name'), name='unique_page_daily_metric')],
            },
        ),
        migrations.CreateModel(
            name='ProductDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('category_name', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('product_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры товара')),
                ('unique_view_visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальные посетители просмотров')),
                ('unique_view_profiles', models.PositiveIntegerField(default=0, verbose_name='Уникальные профили просмотров')),
                ('cart_adds', models.PositiveIntegerField(default=0, verbose_name='Добавления в корзину')),
                ('cart_removes', models.PositiveIntegerField(default=0, verbose_name='Удаления из корзины')),
                ('favorite_adds', models.PositiveIntegerField(default=0, verbose_name='Добавления в избранное')),
                ('favorite_removes', models.PositiveIntegerField(default=0, verbose_name='Удаления из избранного')),
                ('lead_items', models.PositiveIntegerField(default=0, verbose_name='Позиции в заявках')),
                ('lead_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество в заявках')),
                ('lead_count', models.PositiveIntegerField(default=0, verbose_name='Уникальных заявок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дневная метрика товара',
                'verbose_name_plural': 'Дневные метрики товаров',
                'ordering': ('-date', '-product_views'),
                'constraints': [models.UniqueConstraint(fields=('date', 'product'), name='unique_product_daily_metric')],
            },
        ),
    ]
