# Generated by Django 6.0.7 on 2026-09-21 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_productdailymetric_product'),
        ('leads', '0006_preserve_existing_sla'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadScoringState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидается расчёт'), ('ready', 'Рассчитано'), ('error', 'Ошибка расчёта')], default='pending', max_length=10)),
                ('requested_revision', models.PositiveIntegerField(default=1)),
                ('completed_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_state', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'requested_at'], name='scoring_pending_idx')],
            },
        ),
    ]
